<a href="https://colab.research.google.com/github/rahavi-r31/ExporterAI_Chapter_68_analytics/blob/colab/trial_cleaning_chap_58.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# New Section

In [ ]:
import pandas as pd

data=pd.read_excel('/content/52_CHAPTER_COMBINE_EXCEL(1) (version 1).xlsb.xlsx')

In [ ]:
data.info()

In [ ]:
data["SB DATE"] = pd.to_datetime(data["SB DATE"], errors="coerce", dayfirst=True)
data["FOB INR"] = (
    data["FOB INR"]
    .astype(str)
    .str.strip()
    .str.replace(",", "", regex=False)
    .replace("UNKNOWN", None)
    .astype(float)
)

In [ ]:
data['SB DATE'].info()

In [ ]:
data[['SB DATE','FOB INR']]

In [ ]:
data[data.isnull().any(axis=1)].to_csv("/content/entries with null.csv",index=False)

In [ ]:
data.isnull().sum()

In [ ]:
data[["QUANTITY", "FOB INR"]] = data[["QUANTITY", "FOB INR"]].fillna(0)

In [ ]:
data = data.fillna("UNKNOWN")

In [ ]:
data.isnull().sum()

In [ ]:
data.describe(include="all")

In [ ]:
data = data.rename(columns={
    "RITC": "HS_CODE",
    "RITC DISCRIPTION": "PRODUCT_DESCRIPTION",
    "EXPORTER ID": "IEC",
    "COUNTRY OF ORIGIN": "FOREIGN COUNTRY"
})

In [ ]:
data.info()

In [ ]:
unique_importers = data["PORT OF LOADING"].unique()
unique_table = pd.DataFrame(unique_importers, columns=["PORT OF LOADING"])
unique_table.to_csv('/content/port names.csv')

In [ ]:
name_mapping = {
    'BANBASA LCS (INBSAB)': [' BANBASA LCS',' BANBASA LCS (INBSAB)','Banbasa LCS','BANBASA LCS', 'Banbasa', 'BANBASA LCS'],
    'BARHI ICD (INRUG6)':[' BARHI','Barhi ICD','BARHI ICD ','BARHI ICD','ICD BARHI'],
    'AHEMDABAD AIR ACC (INAMD4)':['AHEMDABAD AIR ACC ','AHEMDABAD AIR'],
    'AHEMDABAD ICD (INSBI6)':['Ahemdabad ICD','AHEMDABAD ICD ','AHEMDABAD ICD'],
    'AHMEDABAD APPAREL PARK SEZ':['AHMEDABAD AAP SEZ'],
    'ALBRATOS CFS PRIVATE LIMITED ICD (INAPL6)':['ALBRATOS CFS PVT. LTD. ICD','ALBRATOS CFS PVT. LTD. ICD ','ALBRATOS CFS PVT. LTD. ICD (INAPL6)','ALBRATOS CFS PRIVATE LIMITED ICD'],
    'BADDI ICD (INBDI6)':['BADDI ICD'],
    'BAIRGANIA (INBGUB)': ['BAIRGANIA ','Bairgania','BAIRGANIA'],
    'BANGALORE ACC (INBLR4)':['BANGALORE ACC ','BANGALORE AIR','Bangalore Air','Banglore Air Cargo'],
    'BANGALORE ICD (INWFD6)':['BANGALORE ICD','Bangalore ICD','BANGALORE ICD '],
    'BEHRNI LCS (INBNYB)':['BEHRNI LCS ','BEHRNI LCS','Behrni ICD','BERHNI','Berhni'],
    'CONCOR JODHPUR ICD (INBGK6)':['Bhagat ki Kothi Jodhpur ICD','JODHPUR ICD-BHAGAT','Jodhpur ICD-Bhagat'],
    'THAR DRY PORT JODHPUR ICD (INTHA6)':['THAR DRY PORT JODHPUR ICD ','THAR DRY PORT JODHPUR ICD'],
    'BHIMNAGAR (INBNRB)':['Bhimnagar ','BHIMNAGAR ','BHIMNAGAR'],
    'BHITAMORE (INBTMB)':['BHITAMORE ','BHITHAMORE','Bhithamore'],

    # Additional mappings for remaining ports
    'Acc Kannur': ['Acc Kannur'],
    'ADANI ICD KILARAIPUR DEHLON LUDHIANA': ['KILARAIPUR ADANI ICD','KILARAIPUR ADANI ICD (INQRP6)'],
    'AHMEDABAD AIR': ['Ahmedabad Air','AHMEDABAD AIR'],
    'AHMEDABAD ICD': ['AHMEDABAD ICD'],
    'AHMEDABAD SABARMATI ICD': ['AHMEDABAD SABARMATI ICD'],
    'AMRITSAR ACC (INATQ4)': ['Rajasansi Amritsar'],
    'BHITHAMORE SURSNAD': ['BHITHAMORE SURSNAD'],
    'BIAORA ICD': ['BIAORA ICD'],
    'BIRPARA (INDLOB)': ['BIRPARA','BIRPARA JALPAIGURI','LCS BIRPARA JAPIGURI'],
    'BOMBAY AIR CARGO': ['Bombay Air','Bombay Air Cargo','BOMBAY AIR CARGO'],
    'BORKHEDI ICD (INBOK6)': ['BORKHEDI ICD','Borkhedi ICD','BORKHEDI ICD ','BORKHEDI ICD NAGPUR','ICD BORKHEDI','ICD BORKHEDI (INBOA6)'],
    'BRANDIX INDIA APPAREL CITY PRIVATE SEZ': ['BRANDIX INDIA APPAREL CITY PRIVATE SEZ'],
    'CALICUT ACC (INCCJ4)': ['CALICUT ACC ','CALICUT AIR','Calicut Air','KARIPUR CALICUT','Karipur Calicut'],
    'CHAMURCHI (INCHMB)': ['CHAMURCHI','Chamurchi','CHAMURCHI ','Chamurchi LCS'],
    'CHAWAPAYAL ICD (INCPR6)': ['CHAWAPAYAL ICD','Chawapayal ICD','CHAWAPAYAL ICD ','CHAWAPAYAL ICD SAMRALA','CHAWAPAYAL SAMRALA'],
    'CHEHERTA ICD ': ['CHEHERTA ICD '],
    'CHENNAI AIR CARGO ACC (INMAA4)': ['CHENNAI AIR','Chennai Air Cargo','CHENNAI AIR CARGO','CHENNAI AIR CARGO ACC '],
    'CHENNAI SEA (INMAA1)': ['CHENNAI SEA','Chennai Sea','CHENNAI SEA '],
    'CHETTIPALAYM ICD (INCHE6)': ['CHETTIPALAYM ICD '],
    'CMA CGM LOGISTICS PARK ICD (INCPL6)': ['CMA CGM LOGISTICS PARK ICD','CMA CGM LOGISTICS PARK ICD '],
    'COCHIN AIR CARGO ACC (INCOK4)': ['COCHIN AIR','Cochin Air','COCHIN AIR CARGO ACC '],
    'COCHIN SEA (INCOK1)': ['Cochin','COCHIN SEA','Cochin Sea','COCHIN SEA '],
    'COCHIN SEZ': ['COCHIN SEZ'],
    'COIMBATORE ACC (INCJB4)': ['COIMBATORE','Coimbatore','COIMBATORE ACC ','COIMBATORE AIR','Coimbatore Air','Coimbatore Irugur ICD','Tudiyalur Coimbatore ICD'],
    'CONCOR ICD/MIHAN (INKPK6)': ['CONCOR ICD MIHAN NAGPUR','CONCOR ICD/MIHAN','CONCOR ICD/MIHAN ','Mihan ICD','MIHAN ICD (INKPK6)'],
    'DADRI ICD (INDER6)': ['Dadri ACPL CFS','Dadri CGML','DADRI ICD','DADRI ICD ','Dadri STTPL CFS','Dadri-CGML','Noida Dadri ICD','Noida-Dadri-ICD'],
    'DAPPER ICD': ['DAPPAR ICD','DAPPER','DAPPER ICD'],
    'DARRANGA LCS (INDRGB)': ['DARRANGA','Darranga','Darranga LCS','DARRANGA LCS '],
    'DASHRATH VADODRA ICD (INBRC6)': ['DASHRATH VADODRA ICD '],
    'DELHI AIR CARGO ACC (INDEL4)': ['DELHI ACC','DELHI AIR','Delhi Air','Delhi Air Cargo','DELHI AIR CARGO ACC '],
    'DELHI ICD': ['Delhi PPG ICD','Delhi TKD ICD'],
    'DHANNAD ICD (INDHA6)': ['DHANNAD ICD','DHANNAD ICD ','Indore-Dhannad'],
    'DHARCHULA LCS (INDLAB)': ['DHARCHULA'],
    'DIGHI ICD (INDIG6)': ['DIGHI ICD ','Dighi Pune','PUNE DIGHI ICD'],
    'DURGAPUR ICD (INDUR6)': ['DURGAPUR ICD'],
    'Ennore': ['Ennore'],
    'FALTA-EPZ SEZ': ['FALTA SEZ','FALTA-EPZ SEZ'],
    'GALGALIA (INGALB)': ['GALGALIA','Galgalia','GALGALIA '],
    'GANGAVARAM PORT SEA (INGGV1)': ['Gangavaram Port'],
    'GARI HARSARU ICD (INGHR6)': ['Garhi Harsaru Gurgaon ICD','GARI HARSARU ICD ','Gurgaon ICD','GURGAON ICD/ GARI HARSARU ICD'],
    'LCS GAURIPHANTA (INGAIB)': ['Gauriphanta'],
    'GHOJADANGA LCS (INGJXB)': ['Ghojadanga','GHOJADANGA LCS'],
    'GRFL SAHNEWAL LUDHIANA ICD (INSGF6)': ['GRFL ICD SAHNEWAL','GRFL SAHNEWAL LUDHIANA ICD','GRFL SAHNEWAL LUDHIANA ICD ','Sahnewal GRFL ICD'],
    'GUNTUR MARRIPALAM': ['GUNTUR MARRIPALAM','LIPL ICD Marripalem Guntur','Marripalam ICD','MARRIPALAM ICD (INGNR6)','MARRIPALAM-GUNTUR ICD','MARRIPALAM-GUNTUR ICD (INGNR6)'],
    'LCS Hatisar (INHTSB)': ['Hatisar'],
    'HAZIRA PORT SURAT (INHZA1)': ['Hazira ','HAZIRA PORT SURAT','HAZIRA PORT SURAT ','HAZIRA PORT SURAT ICD'],
    'HTPL ICD KILARAIPUR (INQRH6)': ['HIND TERMINALS ICD KILARAIPUR DEHLON LUDHIANA'],
    'HYDERABAD ACC (INHYD4)': ['Hyderabad','HYDERABAD ACC ','HYDERABAD AIR','Hyderabad Air','Hyderabad Air Cargo'],
    'HYDERABAD ICD (INSNF6)': ['HYDERABAD ICD'],
    'ICD CONCOR DHANDARI KALAN LUDHIANA (INLDH6)': ['ICD CONCOR DHANDARI KALAN LUDHIANA ','POWERKHEDA ICD Dhandari Kalan','PSWC DHANDARI KALAN LUDHIANA','PSWC DHANDARI KALAN LUDHIANA ','PSWC DHANDARI KALAN LUDHIANA (INDDL6)'],
    'ICD KHATUWAS': ['ICD KHATUWAS','KHATUWAS ICD','Khatuwas ICD ','KHATUWAS ICD (INCML6)'],
    'ICDPLIL GHUNGRANA (INGPL6)': ['ICD PLIL Ghungrana'],
    'ICD TONDIARPET': ['ICD TONDIARPET','TONDIAPET ICD','TONDIAPET ICD (INTVT6)'],
    'ICD TUMB': ['ICD TUMB','TUMB ICD','Tumb ICD','TUMB ICD (INSAJ6)'],
    'ICD VARNAMA': ['ICD VARNAMA'],
    'IRUGUR ICD (INIGU6)': ['IRUGUR ICD','Irugur ICD','IRUGUR ICD '],
    'LCS JAIGAON (INJIGB)': ['Jaigaon','Jaigaon LCS ','LCS JAIGAON','LCS JAIGAON '],
    'JAIPUR ACC (INJAI4)': ['JAIPUR','Jaipur','JAIPUR ACC ','JAIPUR AIR'],
    'KANAKPURA ICD (INKKU6)': ['Jaipur ICD-Kanakpura','JAIPUR ICD-KANAKPURA ICD','KANAKPURA ICD ','Kanakpura Jaipur ICD'],
    'JANORI ICD (INJNR6)': ['JANORI','JANORI ICD','Janori ICD'],
    'JATTIPUR ICD (INDWN6)': ['JATTIPUR ICD','JATTIPUR ICD '],
    'JAYANAGAR (INJAYB)': ['JAYANAGAR','Jayanagar','JAYANAGAR '],
    'JHULAGHAT LCS (INJHOB)': ['JHULAGHAT','Jhulaghat LCS','JHULAGHAT PITHORAGARH','Jhulaghat Pithoragarh'],
    'NHAVA SHEVA SEA (INNSA1)': ['JNPT','JNPT/ NHAVA SHEVA SEA','JNPT-MUMBAI','NHAVA SHEVA','NHAVA SHEVA SEA','NHAVA SHEVA SEA '],
    'JOGBANI (INJBNB)': ['JOGBANI','Jogbani','JOGBANI ','Jogbani '],
    'JRY KANPUR ICD (INKNU6)': ['JRY KANPUR ICD (INKNU6)'],
    'KAKINADA SEA (INKAK1)': ['KAKINADA','Kakinada'],
    'KAMARAJAR PORT (INENR1)': ['KAMARAJAR PORT','KAMARAJAR PORT '],
    'KAMARDWISA LCS (INPBLB)': ['KAMARDWISA','KAMARDWISA LCS '],
    'KANDLA SEA (INIXY1)': ['Kandla','KANDLA  EPZ SEZ ','KANDLA SEA'],
    'KARUR ICD (INKAR6)': ['KARUR','Karur ICD','KARUR ICD'],
    'KASHIPUR ICD (INHPI6)': ['KASHIPUR ICD','KASHIPUR ICD ','SANDKHERA ICD KASHIPUR','SANDKHERA KASHIPUR'],
    'KATTUPALLI PORT SEA (INKAT1)': ['KATTUPALLI PORT SEA','KATTUPALLI PORT SEA ','Kattupalli Sea','KATTUPALLI VILLAGE PONNERI TALUK TIRUVALLUR'],
    'KERN ICD MADURAI (INMDU6)': ['KERN ICD MADURAI '],
    'Khunwa': ['Khunwa'],
    'KIADB SEZ HASSAN TEXTILES SEZ': ['KIADB SEZ HASSAN TEXTILES SEZ'],
    'KILARAIPUR ICD (INQRH6)': ['KILARAIPUR ICD','Kilaraipur ICD','KILARAIPUR ICD ','KILARAIPUR ICD (INQRH6)'],
    'KLPPL PANKI': ['KLPPL PANKI','PANKI ICD','Panki ICD','PANKI ICD (INPNK6)'],
    'KOLKATA ACC (INCCU4)': ['KOLKATA ACC ','KOLKATA AIR','Kolkata Air Cargo'],
    'KOLKATA SEA (INCCU1)': ['Calcutta Air','Calcutta Sea','KOLKATA SEA','Kolkata Sea','KOLKATA SEA '],
    'KOTAWALIGHAT ICD': ['KOTAWALIGHAT ICD','Kotawalighat Mohedipur','Mohedipur ICD'],
    'KOTTAYAM ICD': ['KOTTAYAM ICD'],
    'KRIL ICD PALI': ['KRIL ICD PALI','PALI ICD REWARI'],
    'KRISHNAPATNAM PORT SEA (INKRI1)': ['KRISHNAPATNAM','KRISHNAPATNAM PORT SEA','KRISHNAPATNAM PORT SEA ','Krishnapatnam Sea'],
    'KUNAULI (INKNLB)': ['KUNAULI','Kunauli','Kunauli ','KUNAULI '],
    'LCS LAUKAHA/MADHUBANI': ['LCS LAUKAHA/MADHUBANI','Madhubani LCS'],
    'LCS NAGARKATA': ['LCS NAGARKATA','NAGARKATA LCS'],
    'LCS Nepalgunj Road (INNGRB)': ['LCS Nepalgunj Road','LCS Nepalgunj Road ','LCS Nepalgunj Road (INNGRB )','Neaplgunj LCS','NEPALGUNJ ICD','Nepalgunj Road'],
    'LCS PAIPRAUN MADHUBANI': ['LCS PAIPRAUN MADHUBANI','PAIPRAUN MADHUBANI'],
    'LCS THOOTHIBARI / MAHARAJGANJ': ['LCS Thoothibari (INNTVB)','LCS THOOTHIBARI / MAHARAJGANJ'],
    'LOKSAN LCS': ['LOKSAN LCS'],
    'LONI ICD': ['LONI ICD'],
    'LUCKNOW AIR CARGO (INLKO4)': ['Lucknow','LUCKNOW AIR'],
    'LUDHIANA ICD': ['Ludhiana','LUDHIANA ICD','Ludhiana ICD'],
    'MADURAI AIR CARGO (INIXM4)': ['Madras Air','Madras Sea','Madurai','MADURAI AIR'],
    'MAHADIPUR LCS (INMHDB)': ['MAHADIPUR LCS','MAHADIPUR LCS '],
    'MAHINDRA WORLD CITY (JAIPUR) LIMITED - MULTI-PRODUCT SEZ': ['MAHINDRA SEZ/SANGANER','MAHINDRA WORLD CITY (JAIPUR) LIMITED - MULTI-PRODUCT SEZ'],
    'MANDIDEEP ICD (INMDD6)': ['Mandideep','MANDIDEEP ICD','MANDIDEEP ICD '],
    'MANGALORE SEA (INNML1)': ['MANGALORE SEA'],
    'MODINAGAR ICD (INMUZ6)': ['MODINAGAR ICD','MODINAGAR ICD UTTAR PRADESH'],
    'MUMBAI CUSTOM HOUSE SEA (INBOM1)': ['MUMBAI CUSTOM HOUSE SEA','MUMBAI CUSTOM HOUSE SEA '],
    'MUNDRA SEA (INMUN1)': ['Mundra','MUNDRA SEA','MUNDRA SEA '],
    'NAGPUR AIR CARGO (INNAG4)': ['NAGPUR AIR CARGO (INNAG4)'],
    'NOIDA SEZ': ['NOIDA SEZ'],
    'PAKWARA MORADABAD ICD (INMBD6)': ['Pakwara Moradabad','PAKWARA MORADABAD ICD','PAKWARA MORADABAD ICD ','Pakwara-Moradabad'],
    'PALWAL ICD (INPWL6)': ['PALWAL ICD','Palwal ICD','PALWAL ICD '],
    'Pan itanki Naxabari': ['Pan itanki Naxabari'],
    'PANCHI GUJARAN Sonepat ICD': ['PANCHI GUJARAN Sonepat ICD'],
    'Panipat ICD': ['Panipat ICD','SAMALKHA ICD PANIPAT'],
    'PANITANKI-NAXALBARI (INPNTB)': ['PANITANKI-NAXALBARI','Panitanki-Naxalbari ','PANITANKI-NAXALBARI '],
    'PANTNAGAR ICD': ['PANTNAGAR ICD','SIDCUL ICD/ PANTNAGAR ICD'],
    'PATLI ICD (INPTL6)': ['PATLI ICD','Patli ICD','PATLI ICD '],
    'PATPARGANJ ICD (INPPG6)': ['Patparganj','PATPARGANJ ICD'],
    'PETRAPOLE (INPTPB)': ['PETRAPOLE','PETRAPOLE ','Petrapole Road'],
    'PIPAVAV - VICTOR PORT GUJARAT SEA (INPAV1)': ['Pipavav ','PIPAVAV - VICTOR PORT GUJARAT SEA','PIPAVAV - VICTOR PORT GUJARAT SEA ','PIPAVAV VICTOR','Pipavav Victor Port'],
    'PIPRAUN (INKJIB)': ['PIPRAUN','PIPRAUN '],
    'PITHAMPUR ICD (ININD6)': ['Pithampur','PITHAMPUR ICD','Pithampur ICD','PITHAMPUR ICD '],
    'PIYALA ICD (INBFR6)': ['Piyala Ballabhgarh ICD','PIYALA ICD'],
    'POWARKHEDA ICD': ['POWARKHEDA ICD','Powerkheda ICD'],
    'RANAGHAT RAILWAY STATION NADIA (INRNG2)': ['RANAGHAT RAILWAY STATION NADIA '],
    'RAXAUL (INRXLB)': ['RAXAUL','Raxaul','Raxaul ','RAXAUL '],
    'SACHANA ICD (INJKA6)': ['SACHANA ICD','SACHANA ICD VIRAMGAM'],
    'SAHAR AIR CARGO ACC (INBOM4)': ['SAHAR AIR','SAHAR AIR CARGO','SAHAR AIR CARGO ACC '],
    'Sandkhera ICD': ['Sandkhera ICD'],
    'SEEPZ SEZ': ['SEEPZ SEZ'],
    'SEZ/SATYAVEDU & VARDAYYAPALEM MANDAL': ['SEZ/SATYAVEDU & VARDAYYAPALEM MANDAL'],
    'SONABARSA (INSNBB)': ['SONABARSA','Sonabarsa','Sonabarsa ','SONABARSA ','SONBARSA'],
    'SONAULI LCS (INSNLB)': ['SONAULI','Sonauli','SONAULI LCS','Sonauli LCS','SONAULI LCS '],
    'SONEPAT ICD (INBDM6)': ['SONEPAT ICD','Sonepat ICD','SONEPAT ICD '],
    'SRI CITY MULTI PRODUCT SEZ': ['SRI CITY MULTI PRODUCT SEZ'],
    'STARTRACK TERMINAL ICD': ['STARTRACK TERMINAL ICD'],
    'TALEGAON PUNE ICD (INTLG6)': ['Pune Talegoan ICD','TALEGAON PUNE ICD'],
    'THAR DRY PORT ICD/AHMEDABAD GUJARAT ICD (INSAU6)': ['Thar Dry Port ICD Ahmedabad','THAR DRY PORT ICD/AHMEDABAD GUJARAT ICD','Thar Dry Port ICD/Ahmedabad Gujarat ICD','THAR DRY PORT ICD/AHMEDABAD GUJARAT ICD '],
    'THUDIALUR ICD (INTDE6)': ['THUDIALUR ICD ','THUDIALUR ICD/ COIMBATORE ICD'],
    'TIKONIA LCS (INTKNB)': ['TIKONIA','Tikonia','TIKONIA LCS','Tikonia LCS','TIKONIA LCS '],
    'TIRUCHIRAPALLI AIR CARGO (INTRZ4)': ['Tiruchirapalli','TIRUCHIRAPALLI AIR','Tiruchirapalli Air','TIRUCHIRAPALLI AIR CARGO '],
    'TIRUPPUR - THOTTIPLAYAM ICD': ['TIRUPPUR - THOTTIPLAYAM ICD','Tiruppur Chettipalayam CFS'],
    'TRIVANDRUM ACC (INTRV4)': ['TRIVANDRUM ACC ','TRIVANDRUM AIR','Trivendrum Air Cargo'],
    'TUGLAKABAD ICD (INTKD6)': ['Tughlakabad','TUGHLAKABAD ICD','TUGLAKABAD ICD','TUGLAKABAD ICD '],
    'TUTICORIN ICD (INTUT6)': ['Tuticorin ICD','TUTICORIN ICD','TUTICORIN ICD '],
    'TUTICORIN SEA (INTUT1)': ['TUTICORIN SEA','Tuticorin Sea','TUTICORIN SEA '],
    'VIZAG SEA (INVTZ1)': ['VIZAG SEA','Vizag Sea','VIZAG SEA ']
}

expanded_mapping = {}
for canonical, variations in name_mapping.items():
    for v in variations:
        expanded_mapping[v] = canonical

data['PORT OF LOADING'] = data['PORT OF LOADING'].replace(expanded_mapping)


print("Port name mapping applied successfully!")
print(f"Number of unique port names after mapping: {data['PORT OF LOADING'].nunique()}")
print("\nSample of standardized port names:")
print(data['PORT OF LOADING'].value_counts().head(10))
print(data['PORT OF LOADING'].describe())

In [ ]:
unique_importers = data["PORT OF LOADING"].unique()
unique_table = pd.DataFrame(unique_importers, columns=["PORT OF LOADING"])
unique_table.to_csv('/content/port names ad.csv')

In [ ]:
unique_importers = data["FOREIGN COUNTRY"].unique()
unique_table = pd.DataFrame(unique_importers, columns=["FOREIGN COUNTRY"])
unique_table.to_csv('/content/foreign country names.csv')

In [ ]:
import pandas as pd

name_mapping = {
    'United States': [
        'UNITED STATES', 'United States', 'UNITED STATES OF AMERICA',
        'United States of America', 'UNITED STAT', 'UNITED STATE'
    ],
    'United Kingdom': [
        'UNITED KINGDOM', 'United Kingdom', 'UNITED KING', 'UNITED KINGD'
    ],
    'United Arab Emirates': [
        'UNITED ARAB EMIRATES', 'United Arab Emirates', 'UNITED ARAB EMIRATES ',
        'UNITED ARAB', 'UNITED ARABÂ ', 'UNITED ARAB E'
    ],
    'Germany': ['GERMANY', 'Germany'],
    'France': ['FRANCE', 'France', 'FRANCE '],
    'Italy': ['ITALY', 'Italy', 'ITALY '],
    'Spain': ['SPAIN', 'Spain', 'SPAIN '],
    'Switzerland': ['SWITZERLAND', 'Switzerland', 'SWITZERLAND '],
    'Austria': ['AUSTRIA', 'Austria', 'AUSTRIA '],
    'Belgium': ['BELGIUM', 'Belgium', 'BELGIUM '],
    'Netherlands': ['NETHERLANDS', 'Netherlands', 'NETHERLANDS '],
    'Poland': ['POLAND', 'Poland', 'POLAND '],
    'Norway': ['NORWAY', 'Norway', 'NORWAY '],
    'Sweden': ['SWEDEN', 'Sweden', 'SWEDEN '],
    'Denmark': ['DENMARK', 'Denmark', 'DENMARK '],
    'Finland': ['FINLAND', 'Finland', 'FINLAND '],
    'Iceland': ['ICELAND', 'Iceland'],
    'Ireland': ['IRELAND', 'Ireland', 'IRELAND '],
    'Portugal': ['PORTUGAL', 'Portugal', 'PORTUGAL '],
    'Greece': ['GREECE', 'Greece', 'GREECE '],
    'Malta': ['MALTA', 'Malta', 'MALTA '],
    'Cyprus': ['CYPRUS', 'Cyprus', 'CYPRUS '],
    'Luxembourg': ['LUXEMBOURG ', 'Luxembourg'],
    'Monaco': ['MONACO'],
    'Canada': ['CANADA', 'Canada', 'CANADA '],
    'Australia': ['AUSTRALIA', 'Australia', 'AUSTRALIA '],
    'New Zealand': ['NEW ZEALAND', 'New Zealand', 'NEW ZEALAND '],
    'Japan': ['JAPAN', 'Japan', 'JAPAN '],
    'South Korea': [
        'KOREA,REPUBLIC OF', 'KOREA, REPUBLIC OF', 'Korea South Republic',
        'South Korea', 'KOREAREPUBLIC OF', 'Republic of Korea',
        'Korea, Republic Of', 'REPUBLIC OF KOREA', 'Republic Of Korea',
        'KOREA REPUBLIC OF', 'KOREA,REPUBLIC OF ', 'South Korea', 'SOUTH KOREA'
    ],
    'North Korea': [
        'North Korea', 'KOREA,DEMOCRATIC PEOPLE\'S REPUBLIC OF ',
        'KOREA DEMOCRATIC PEOPLES REPUBLIC OF'
    ],
    'China': ['CHINA', 'China', 'CHINA '],
    'Hong Kong': ['HONG KONG', 'Hong Kong', 'HONG KONG ', 'Hongkong', 'HONGKONG'],
    'Taiwan': ['TAIWAN', 'Taiwan', 'TAIWAN '],
    'Singapore': ['SINGAPORE', 'Singapore', 'SINGAPORE '],
    'Malaysia': ['MALAYSIA', 'Malaysia', 'MALAYSIA '],
    'Thailand': ['THAILAND', 'Thailand', 'THAILAND '],
    'Philippines': ['PHILIPPINES', 'Philippines', 'PHILIPPINES '],
    'Indonesia': ['INDONESIA', 'Indonesia', 'INDONESIA '],
    'Vietnam': [
        'VIETNAM, DEMOCRATIC REP. OF', 'Vietnam', 'VIETNAM',
        'Vietnam, Democratic Rep. Of', 'VIETNAM DEMOCRATIC REP. OF',
        'VIETNAM, DEMOCRATIC REP. OF ', 'VIETNAM DEMOCRATIC REP OF',
        'YEMEN DEMOCRATIC'
    ],
    'Cambodia': ['CAMBODIA', 'Cambodia', 'CAMBODIA '],
    'Myanmar': ['MYANMAR', 'Myanmar', 'MYANMAR '],
    'Brunei': ['BRUNEI', 'Brunei', 'BRUNEI ', 'Brunei Darussalam'],
    'Bangladesh': ['BANGLADESH', 'Bangladesh', 'BANGLADESH '],
    'Sri Lanka': ['SRI LANKA', 'Sri Lanka', 'SRI LANKA '],
    'Nepal': ['NEPAL', 'Nepal', 'NEPAL '],
    'Bhutan': ['BHUTAN', 'Bhutan', 'BHUTAN '],
    'Maldives': ['MALDIVES', 'Maldives', 'MALDIVES '],
    'India': [],  # Add variations if present in your data
    'Pakistan': ['PAKISTAN', 'Pakistan', 'PAKISTAN '],
    'Afghanistan': ['AFGHANISTAN', 'Afghanistan', 'AFGHANISTAN '],
    'Iran': ['IRAN', 'Iran', 'IRAN '],
    'Iraq': ['IRAQ', 'Iraq'],
    'Syria': ['SYRIA', 'Syria', 'SYRIA '],
    'Turkey': ['TURKEY', 'Turkey', 'TURKEY '],
    'Israel': ['ISRAEL', 'Israel', 'ISRAEL '],
    'Jordan': ['JORDAN', 'Jordan', 'JORDAN '],
    'Lebanon': ['LEBANON', 'Lebanon', 'LEBANON '],
    'Saudi Arabia': ['SAUDI ARABIA', 'Saudi Arabia', 'SAUDI ARABIA '],
    'Kuwait': ['KUWAIT', 'Kuwait', 'KUWAIT '],
    'Qatar': ['QATAR', 'Qatar', 'Qatar'],
    'Bahrain': ['BAHRAIN', 'Bahrain', 'BAHRAIN '],
    'Oman': ['OMAN', 'Oman', 'Oman', 'OMAN '],
    'Yemen': ['YEMEN, DEMOCRATIC ', 'Yemen', 'YEMEN', 'Yemen, Democratic', 'YEMEN DEMOCRATIC'],
    'Egypt': ['EGYPT', 'Egypt', 'EGYPT '],
    'Sudan': ['SUDAN', 'Sudan', 'SUDAN '],
    'South Sudan': ['SOUTH SUDAN', 'South Sudan', 'SOUTH SUDAN '],
    'Libya': ['LIBYAN ARAB REPUBLIC'],
    'Tunisia': ['TUNISIA', 'Tunisia', 'TUNISIA '],
    'Algeria': ['ALGERIA', 'Algeria', 'ALGERIA '],
    'Morocco': ['MOROCCO', 'Morocco', 'MOROCCO '],
    'South Africa': ['SOUTH AFRICA', 'South Africa', 'SOUTH AFRICA '],
    'Nigeria': ['NIGERIA', 'Nigeria', 'NIGERIA '],
    'Ghana': ['GHANA', 'Ghana', 'GHANA '],
    'Kenya': ['KENYA', 'Kenya', 'KENYA '],
    'Tanzania': ['TANZANIA', 'Tanzania', 'TANZANIA '],
    'Uganda': ['UGANDA', 'Uganda', 'UGANDA '],
    'Ethiopia': ['ETHIOPIA', 'Ethiopia', 'ETHIOPIA '],
    'Somalia': ['SOMALIA', 'Somalia', 'SOMAALIA', 'SOMAALIA '],
    'Djibouti': ['DJIBOUTI', 'Djibouti', 'DJIBOUTI '],
    'Rwanda': ['RWANDA', 'Rwanda', 'RWANDA '],
    'Burundi': ['BURUNDI', 'Burundi'],
    'Democratic Republic of the Congo': [
        'CONGO, THE DEMOCRATIC REPUBLIC OF THE',
        'Congo, The Democratic Republic Of The',
        'CONGO THE DEMOCRATIC REPUBLIC OF THE',
        'Congo the Democratic Republic of the',
        'CONGO, THE DEMOCRATIC REPUBLIC OF THE '
    ],
    'Republic of the Congo': ['CONGO', 'Congo', 'CONGO ', 'CONGO D REPULIC', 'CONGO (KINSHASA)'],
    'Central African Republic': ['CENTRAL AFRICAN REPULIC ', 'Central African Republic'],
    'Chad': ['CHAD', 'Chad', 'CHAD '],
    'Niger': ['NIGER', 'Niger', 'NIGER '],
    'Mali': ['MALI', 'Mali', 'MALI '],
    'Burkina Faso': ['BURKINA FASO', 'Burkina Faso', 'BURKINA FASO '],
    'Senegal': ['SENEGAL', 'Senegal', 'SENEGAL '],
    'Gambia': ['GAMBIA', 'Gambia', 'GAMBIA '],
    'Guinea-Bissau': ['Guinea Bissau'],
    'Guinea': ['GUINEA', 'Guinea', 'GUINEA '],
    'Sierra Leone': ['SIERRA LEONA', 'SIERRA LEONE', 'Sierra Leone', 'Sierra Leona', 'SIERRA LEONA '],
    'Liberia': ['LIBERIA', 'Liberia', 'LIBERIA '],
    'Côte d\'Ivoire': [
        'COTE D IVOIRE', 'COTE D IVOIRE ', 'Cote D Ivoire ',
        'Ivory Coast', 'Cote D Ivoire', 'Cote D Ivoire Ivory Coast'
    ],
    'Ghana': ['GHANA', 'Ghana', 'GHANA '],
    'Togo': ['TOGO', 'Togo', 'TOGO '],
    'Benin': ['BENIN', 'Benin', 'BENIN '],
    'Cameroon': ['CAMEROON', 'Cameroon', 'CAMEROON '],
    'Equatorial Guinea': ['EQUATORIAL GUINEA', 'EQUATORIAL GUINEA '],
    'Gabon': ['GABON', 'Gabon', 'GABON '],
    'Angola': ['ANGOLA', 'Angola', 'ANGOLA '],
    'Zambia': ['ZAMBIA', 'Zambia', 'ZAMBIA '],
    'Zimbabwe': ['ZIMBABWE'],
    'Botswana': ['BOTSWANA', 'Botswana', 'BOTSWANA '],
    'Namibia': ['NAMBIA', 'Namibia ', 'Namibia'],
    'Lesotho': ['LESOTHO', 'Lesotho', 'LESOTHO '],
    'Swaziland': ['SWAZILAND', 'Swaziland', 'SWAZILAND '],
    'Madagascar': ['MADAGASCAR', 'Madagascar', 'MADAGASCAR '],
    'Mauritius': ['MAURITIUS', 'Mauritius', 'MAURITIUS '],
    'Seychelles': ['SEYCHELLES', 'Seychelles', 'SEYCHELLES '],
    'Comoros': ['COMOROS', 'Comoros', 'COMOROS ', 'COMORO ISLANDS'],
    'Mayotte': ['MAYOTTE', 'Mayotte', 'MAYOTTE '],
    'Reunion': ['REUNION', 'Reunion', 'REUNION '],
    'Mauritania': ['MAURITANIA', 'Mauritania', 'MAURITANIA '],
    'Malawi': ['MALAWI', 'Malawi', 'MALAWI '],
    'Mozambique': ['MOZAMBIQUE', 'Mozambique', 'MOZAMBIQUE '],
    'Brazil': ['BRAZIL', 'Brazil', 'BRAZIL '],
    'Argentina': ['ARGENTINA', 'Argentina', 'ARGENTINA '],
    'Chile': ['CHILE', 'Chile', 'CHILE '],
    'Peru': ['PERU', 'Peru', 'PERU '],
    'Uruguay': ['URUGUAY', 'Uruguay', 'URUGAY', 'URUGAY '],
    'Paraguay': ['PARAGUAY', 'Paraguay', 'PARAGUAY '],
    'Bolivia': ['BOLIVIA'],
    'Colombia': ['COLOMBIA', 'Colombia', 'COLOMBIA '],
    'Venezuela': ['VENEZUELA', 'Venezuela', 'VENEZUELA '],
    'Ecuador': ['ECUADOR', 'Ecuador', 'ECUADOR '],
    'Guyana': ['GUYANA', 'Guyana', 'GUYANA '],
    'Suriname': ['SURINAM', 'Suriname', 'SURINAM ', 'SURINAME'],
    'French Guiana': ['French Guiana'],
    'Mexico': ['MEXICO', 'Mexico', 'MEXICO '],
    'Guatemala': ['GAUTEMALA', 'Guatemala', 'GUATEMALA', 'GAUTEMALA '],
    'Belize': ['BELIZE', 'BELIZE '],
    'Honduras': ['HONDURAS', 'Honduras', 'HONDURAS '],
    'El Salvador': ['EL SALVADOR', 'El Salvador', 'EL SALVADOR '],
    'Nicaragua': ['NICARAGUA', 'Nicaragua', 'NICARAGUA '],
    'Costa Rica': ['COSTA RICA', 'Costa Rica', 'COSTA RICA '],
    'Panama': ['PANAMA', 'Panama', 'PANAMA '],
    'Cuba': ['Cuba'],
    'Jamaica': ['JAMAICA', 'Jamaica', 'JAMAICA '],
    'Haiti': ['HAITI', 'Haiti', 'HAITI '],
    'Dominican Republic': [
        'DOMINICAN REPULIC', 'Dominican Repulic', 'DOMINICAN REPULIC ',
        'Dominican Republic', 'DOMINICAN REPUBLIC', 'Dominican Repulic ',
        'DOMINICAN REPUBLIC1', 'DOMINICAN REPULIC', 'DOMINICAN REP'
    ],
    'Puerto Rico': ['PUERTO RICO'],
    'Trinidad and Tobago': [
        'TRINIDAD & TOBAGO', 'Trinidad and Tobago', 'TRINIDAD TOBAGO',
        'TRINIDAD & TOBAGO ', 'TRINIDAD AND TOBAGO', 'Trinidad Tobago ',
        'Trinidad & Tobago'
    ],
    'Barbados': ['BARBADOS', 'Barbados', 'BARBADOS '],
    'Saint Vincent and the Grenadines': [
        'SAINT VINCENT AND GRENADINES', 'Saint Vincent And The Grenadines',
        'ST VINCENT', 'ST VINCENT '
    ],
    'Grenada': ['GRENADA '],
    'Dominica': ['DOMINICA', 'Dominica'],
    'Antigua and Barbuda': ['Antigua '],
    'Saint Kitts and Nevis': [],
    'Bahamas': ['BAHAMAS', 'Bahamas', 'BAHAMAS '],
    'Bermuda': ['BERMUDA', 'BERMUDA '],
    'Cayman Islands': ['CAYMAN ISLANDS', 'Cayman'],
    'Turks and Caicos Islands': [],
    'Virgin Islands': [],
    'Montserrat': ['MONTSERRAT'],
    'Anguilla': [],
    'Saint Lucia': [],
    'Martinique': ['MARTINIQUE', 'Martinique', 'MARTINIQUE '],
    'Guadeloupe': ['GUADELOUPE', 'Guadeloupe', 'GUADELOUPE '],
    'Saint Barthélemy': ['ST. BARTHELEMY'],
    'Netherlands Antilles': ['NETHERLANDS ANTILLES', 'Netherlands Antilles', 'NETHERLANDS ANTILLES '],
    'Aruba': ['ARUBA'],
    'Russia': ['RUSSIA', 'Russia', 'RUSSIA ', 'Russian Federation'],
    'Ukraine': ['UKRAINE', 'Ukraine'],
    'Belarus': [],
    'Moldova': ['MOLDOVA,REPUBLIC OF'],
    'Romania': ['ROMANIA', 'Romania', 'ROMANIA '],
    'Bulgaria': ['BULGARIA', 'Bulgaria', 'BULGARIA '],
    'Serbia': ['SERBIA', 'Serbia', 'SERBIA '],
    'Montenegro': ['MONTENEGRO', 'Montenegro', 'MONTENEGRO '],
    'North Macedonia': ['Macedonia,The Former Yugoslav Republic Of'],
    'Kosovo': ['KOSOVO'],
    'Bosnia and Herzegovina': [],
    'Croatia': ['CROATIA', 'Croatia', 'CROATIA '],
    'Slovenia': ['SLOVENIA', 'Slovenia', 'SLOVENIA '],
    'Slovakia': ['SLOVAKIA', 'Slovakia', 'SLOVAK REPUBLIC', 'Slovak Republic', 'SLOVAK REPUBLIC '],
    'Czech Republic': ['CZECH REPUBLIC', 'Czech Republic', 'CZECH REPUBLIC '],
    'Hungary': ['HUNGARY', 'Hungary', 'HUNGARY '],
    'Estonia': ['Estonia'],
    'Latvia': ['LATVIA', 'Latvia', 'LATVIA '],
    'Lithuania': ['LITHUANIA', 'Lithuania', 'LITHUANIA '],
    'Georgia': ['GEORGIA', 'Georgia', 'GEORGIA '],
    'Armenia': ['ARMENIA', 'Armenia'],
    'Azerbaijan': ['AZARBAIJAN', 'Azarbaijan', 'AZARBAIJAN ', 'Azerbaijan'],
    'Kazakhstan': ['KAZAKISTAN', 'Kazakhstan', 'KAZAKHSTAN'],
    'Kyrgyzstan': ['KYRGHYSTAN', 'Kyrghystan', 'Kyrgyzstan', 'KYRGYZSTAN', 'KYRGHYSTAN '],
    'Tajikistan': ['TAJIKISTAN'],
    'Turkmenistan': [],
    'Uzbekistan': ['UZBEKISTAN', 'Uzbekistan', 'UZBEKISTAN '],
    'Mongolia': ['MONGOLIA'],
    'Albania': ['ALBANIA', 'Albania'],
    'Fiji': ['FIJI', 'Fiji', 'FIJI '],
    'Papua New Guinea': ['PAPUA NEW GUINEA', 'Papua New Guinea', 'PAPUA NEW GUINEA '],
    'New Caledonia': ['NEW CALEDONIA', 'New Caledonia', 'NEW CALEDONIA '],
    'Vanuatu': ['VANUATU'],
    'Solomon Islands': [],
    'Samoa': ['SAMOA', 'SAMOA '],
    'Tonga': [],
    'Kiribati': ['KIRIBATI'],
    'Tuvalu': [],
    'Marshall Islands': ['MARSHALL ISLANDS'],
    'Micronesia': [],
    'Palau': [],
    'Nauru': [],
    'Cook Islands': [],
    'French Polynesia': ['FRENCH POLYNESIA', 'French Polynesia ', 'French Polynesia'],
    'Wallis and Futuna': ['WALLIS AND FUTUNA ISLANDS '],
    'Gibraltar': ['GIBRALTAR'],
    'Greenland': ['Greenland'],
    'Faroe Islands': [],
    'Cocos (Keeling) Islands': ['COCOS (KEELING ISLANDS)'],
    'Christmas Island': [],
    'Norfolk Island': [],
    'Heard Island and McDonald Islands': [],
    'Bouvet Island': [],
    'South Georgia and the South Sandwich Islands': [],
    'British Indian Ocean Territory': [],
    'United States Minor Outlying Islands': [
        'UNITED STATES MINOR OUTLAYING ISLANDS ',
        'United States Minor Outlaying Islands'
    ],
    'Macao': ['MACAO ISLANDS'],
    'Serbia and Montenegro': ['Serbia And Montenegro'],
}

# Create expanded mapping
expanded_mapping = {}
for canonical, variations in name_mapping.items():
    for v in variations:
        expanded_mapping[v] = canonical

# Replace the country names in the data
data['FOREIGN COUNTRY'] = data['FOREIGN COUNTRY'].replace(expanded_mapping)


# Display the unique values after replacement to verify
print("Unique country names after standardization:")
print(sorted(data['FOREIGN COUNTRY'].unique()))

# Optional: Save the cleaned data
data.to_csv('cleaned_foreign_country_names.csv', index=False)

In [ ]:
data['FOREIGN COUNTRY'] = data['FOREIGN COUNTRY'].str.upper()

In [ ]:
print(f"Number of unique port names after mapping: {data['FOREIGN COUNTRY'].nunique()}")
print("\nSample of standardized port names:")
print(data['FOREIGN COUNTRY'].value_counts().head(10))
print(data['FOREIGN COUNTRY'].describe())

In [ ]:
unique_importers = data["FOREIGN COUNTRY"].unique()
unique_table = pd.DataFrame(unique_importers, columns=["FOREIGN COUNTRY"])
unique_table.to_csv('/content/foreign country names ad.csv')

In [ ]:
manual_replacements = {
    ".NEPAL": "UNKNOWN",
    ".INDIA": "UNKNOWN",
    ".BANGALADESH": "UNKNOWN",
    "?lesund": "Ålesund",
    "?st? nad Orlic?": "Ústí nad Orlicí",
    "¿st¿ nad Orlic¿": "Ústí nad Orlicí",
    "nana": "UNKNOWN",
    "NA": "UNKOWN"
}

def clean_name(name):
    if pd.isna(name):
        return name
    name = str(name).strip()
    return manual_replacements.get(name, name)

# Apply cleaning to relevant columns
data['PORT OF DISCHARGE'] = data['PORT OF DISCHARGE'].apply(clean_name)

In [ ]:
data.info()

In [ ]:
pip install rapidfuzz

In [ ]:
import pandas as pd
from rapidfuzz import process, fuzz

# --- Step 1: Normalisation Function ---
def normalise_importer(name: str) -> str:
    if pd.isna(name):
        return "UNKNOWN"

    name = str(name).strip().upper()
    # Remove unwanted punctuation
    name = pd.Series(name).str.replace(r"[.,’’()/]", "", regex=True).iloc[0]
    # Replace multiple spaces
    name = pd.Series(name).str.replace(r"\s+", " ", regex=True).iloc[0]
    # Replace rows with only symbols -> TO ORDER
    if pd.Series(name).str.match(r"^[^\w]*$").iloc[0]:
        return "TO ORDER"
    # Normalise variations of "TO ORDER"
    name = pd.Series(name).str.replace(r"TO\s+(THE\s+)?ORDER(\s+OF.*)?", "TO ORDER", regex=True).iloc[0]
    return name

# --- Step 2: Apply Normalisation ---
data["Importer_Clean"] = data["IMPORTER NAME"].apply(normalise_importer)

# --- Step 3: Drop duplicates + sort ---
unique_importers = sorted(data["Importer_Clean"].drop_duplicates())

# --- Step 4: Fuzzy Matching Clusters ---
def fuzzy_group(names, threshold=85):
    groups = {}
    visited = set()

    for name in names:
        if name in visited:
            continue
        # Find matches above threshold
        matches = process.extract(name, names, scorer=fuzz.token_sort_ratio, limit=None)
        cluster = [m[0] for m in matches if m[1] >= threshold]
        for c in cluster:
            visited.add(c)
            groups[c] = name   # assign finalised name = first match (anchor)
    return groups

groups = fuzzy_group(unique_importers)

# --- Step 5: Map back to dataframe ---
data["Importer_Final"] = data["Importer_Clean"].map(groups).fillna(data["Importer_Clean"])

In [ ]:
data

In [ ]:
import pandas as pd
from rapidfuzz import process, fuzz

# -------------------------------
# Step 1: Load and clean data
# -------------------------------
official_df = pd.read_excel("/content/official_port_names.xlsx")

countries_df = pd.read_csv(
    '/content/countries.csv',
    sep=";",
    quotechar='"',
    encoding="latin1"
)  # cols: full_name, code

country_map = dict(zip(
    countries_df['full_name'].str.upper().str.strip(),
    countries_df['code'].str.upper().str.strip()
))

# Clean data
data['PORT OF DISCHARGE'] = data['PORT OF DISCHARGE'].astype(str).str.strip().str.upper()
data['FOREIGN COUNTRY'] = data['FOREIGN COUNTRY'].astype(str).str.strip().str.upper()
data['country_code'] = data['FOREIGN COUNTRY'].map(country_map)

# -------------------------------
# Step 2: Fuzzy matching restricted to country
# -------------------------------
def get_port_match(row, threshold=85):
    port = row['PORT OF DISCHARGE']
    country_code = row['country_code']

    # Filter official ports by country code
    candidates = official_df.loc[official_df['COUNTRY'] == country_code, 'PORT_NAME']
    candidates = [c.upper() for c in candidates]

    if not candidates:
        return {"Final_Port": None, "Score": None, "Status": "NO_CANDIDATES",
                "Official_Country_Code": None}

    result = process.extractOne(port, candidates, scorer=fuzz.ratio)
    if result:
        match, score, _ = result
        if score >= threshold:
            return {"Final_Port": match, "Score": score, "Status": "OK",
                    "Official_Country_Code": country_code}
        else:
            return {"Final_Port": None, "Score": score, "Status": "LOW_CONFIDENCE",
                    "Official_Country_Code": country_code}
    else:
        return {"Final_Port": None, "Score": None, "Status": "NO_MATCH",
                "Official_Country_Code": country_code}

results = data.apply(get_port_match, axis=1)
data = pd.concat([data, results.apply(pd.Series)], axis=1).reset_index(drop=True)

# -----------------------------------
# Extra conditions
# -----------------------------------

# Boolean: True if final port is different from raw
data['Port_Changed'] = data['Final_Port'].notna() & data['PORT OF DISCHARGE'].ne(data['Final_Port'])

# Country mismatch flag (exact matches only, no fuzzy)
data = data.merge(
    official_df[['PORT_NAME', 'COUNTRY']],
    left_on='PORT OF DISCHARGE',
    right_on='PORT_NAME',
    how='left',
    suffixes=('', '_Official')
)

data['Country_Mismatch'] = (
    data['PORT_NAME'].notna() &
    data['country_code'].ne(data['COUNTRY'])
)

# Keep only finalised OK matches
df_final = data[data['Status'] == "OK"].copy()

In [ ]:
data.head()

In [ ]:
from rapidfuzz import process, fuzz

countries_df = pd.read_csv(
    '/content/countries.csv',
    sep=";",
    quotechar='"',
    encoding="latin1"
)
country_map = dict(zip(countries_df['full_name'].str.upper().str.strip(),
                       countries_df['code'].str.upper().str.strip()))

official_df = pd.read_excel('/content/official_port_names.xlsx')
official_ports = [name.upper() for name in official_df['PORT_NAME'].tolist()]

def get_possible_matches(name, choices, threshold=85):
    if pd.isna(name):
        return []
    cleaned_name = str(name).strip().upper().lstrip('.')
    matches = process.extract(cleaned_name, choices, scorer=fuzz.ratio, limit=None)
    return [m[0] for m in matches if m[1] >= threshold and m[0].upper() != cleaned_name]

data['Suggested_Port_Match'] = data['PORT OF DISCHARGE'].apply(lambda x: get_possible_matches(x, official_ports))

data['Country_Code'] = data['FOREIGN COUNTRY'].str.upper().str.strip().map(country_map)

df = data.merge(
    official_df[['PORT_NAME', 'COUNTRY']],
    left_on=data['Suggested_Port_Match'].str[0],
    right_on='PORT_NAME',
    how='left'
).rename(columns={'COUNTRY': 'Official_Country_Code'})

In [ ]:
df.to_csv('/content/port_match.csv')

In [ ]:
import pandas as pd
from rapidfuzz import process, fuzz

# --- Step 1: Normalisation Function ---
def normalise_importer(name: str) -> str:
    if pd.isna(name):
        return "UNKNOWN"

    name = str(name).strip().upper()
    # Remove unwanted punctuation
    name = pd.Series(name).str.replace(r"[.,’’()/]", "", regex=True).iloc[0]
    # Replace multiple spaces
    name = pd.Series(name).str.replace(r"\s+", " ", regex=True).iloc[0]
    # Replace rows with only symbols -> TO ORDER
    if pd.Series(name).str.match(r"^[^\w]*$").iloc[0]:
        return "TO ORDER"
    # Normalise variations of "TO ORDER"
    name = pd.Series(name).str.replace(r"TO\s+(THE\s+)?ORDER(\s+OF.*)?", "TO ORDER", regex=True).iloc[0]
    return name

# --- Step 2: Apply Normalisation ---
data["Importer_Clean"] = data["importer"].apply(normalise_importer)

# --- Step 3: Drop duplicates + sort ---
unique_importers = sorted(data["Importer_Clean"].drop_duplicates())

# --- Step 4: Fuzzy Matching Clusters ---
def fuzzy_group(names, threshold=85):
    groups = {}
    visited = set()

    for name in names:
        if name in visited:
            continue
        # Find matches above threshold
        matches = process.extract(name, names, scorer=fuzz.token_sort_ratio, limit=None)
        cluster = [m[0] for m in matches if m[1] >= threshold]
        for c in cluster:
            visited.add(c)
            groups[c] = name   # assign finalised name = first match (anchor)
    return groups

groups = fuzzy_group(unique_importers)

# --- Step 5: Map back to dataframe ---
data["Importer_Final"] = data["Importer_Clean"].map(groups).fillna(data["Importer_Clean"])

In [ ]:
import pandas as pd
from rapidfuzz import fuzz, process

# --- Cleaning function ---
def clean_importer(name: str) -> str:
    if pd.isna(name):
        return ""
    name = name.strip().upper()
    name = pd.Series(name).str.replace(r"[.,’’()/]", "", regex=True).iloc[0]
    name = pd.Series(name).str.replace(r"\s+", " ", regex=True).iloc[0]

    # Handle "TO ORDER" and "M/S"
    name = pd.Series(name).str.replace(
        r"TO\s+(THE\s+)?ORDER(\s+OF.*)?", "TO ORDER", regex=True
    ).str.replace(r"^M/?S\.?\s*", "", regex=True, case=False).iloc[0]

    # Common replacements
    rules = {
        r"\bL\s*T\s*D\b": "LTD",
        r"\bLIMITED\b": "LTD",
        r"\bLIM\b": "LTD",
        r"\bP\s*V\s*T\b": "PVT",
        r"\bPRIVATE\b": "PVT",
        r"\bC\s*O\b": "CO",
        r"\bCOMPANY\b": "CO",
        r"\bINCORPORATED\b": "INC",
        r"\bP\s*L\s*C\b": "PLC",
        r"\bPUBLIC\s+LTD\b": "PLC",
        r"\bL\s*L\s*C\b": "LLC",
        r"\bF\s*Z\s*C\b": "FZC",
    }
    for pattern, repl in rules.items():
        name = pd.Series(name).str.replace(pattern, repl, regex=True).iloc[0]

    return name.strip()


# --- Apply cleaning ---
data["Final_Importer"] = data["IMPORTER NAME"].apply(clean_importer)

# --- Get unique names only ---
unique_names = pd.Series(data["Final_Importer"].unique(), name="Importer")

# --- Compute pairwise similarity once ---
# This produces a dataframe of all scores
scores = process.cdist(
    unique_names.tolist(),
    unique_names.tolist(),
    scorer=fuzz.ratio,
    workers=-1  # use all CPU cores
)

# --- Build mapping dictionary ---
threshold = 85
mapping = {}
for i, name in enumerate(unique_names):
    possible = [
        unique_names[j]
        for j, score in enumerate(scores[i])
        if score >= threshold and name != unique_names[j]
    ]
    mapping[name] = possible

# --- Map back to original dataframe ---
data["Possible_Matches"] = data["Final_Importer"].map(mapping)

# --- Save final ---
final_df = data.copy()
final_df["Possible_Matches"] = final_df["Possible_Matches"].apply(lambda x: tuple(x) if isinstance(x, list) else x)

final_df = final_df[["Final_Importer", "Possible_Matches"]].drop_duplicates()
final_df.to_csv("cleaned_importers.csv", index=False)

In [ ]:
mask_unknown = data.eq("UNKNOWN").any(axis=1)
unknown_rows = data[mask_unknown]
known_rows   = data[~mask_unknown]

known_rows = known_rows.drop_duplicates(keep="first")

data = pd.concat([known_rows, unknown_rows], ignore_index=True)

In [ ]:
col = ['IEC', 'EXPORTER NAME']
expiec = known_rows.drop_duplicates(subset=col)
db = expiec.groupby('EXPORTER NAME')['IEC'].nunique().reset_index()
multi_iec = db[db['IEC'] > 1]
print(multi_iec)
multi_iec.to_csv('/content/exporters with mulple iec.csv')

In [ ]:
db = expiec.groupby('IEC')['EXPORTER NAME'].nunique().reset_index()
multi_iec = db[db['EXPORTER NAME'] > 1]
print(multi_iec)
multi_iec.to_csv('/content/iec with multiple exporter names.csv')

In [ ]:
from rapidfuzz import process
reference_file = r"C:\Users\karti\Downloads\countries.csv"
ref_df = pd.read_csv(reference_file)    # reference with "name" + "iso3"

# Normalize reference names for matching
ref_df["name_normalized"] = ref_df["name"].str.strip().str.lower()

manual_map = {
    "united states": "United States of America",
    "u.s.a": "United States of America",
    "usa": "United States of America",
    "us": "United States of America",
    "america": "United States of America",
    "turkey": "Türkiye",
    "kyr": "KYRGYZ REPUBLIC",
    "uae": "United Arab Emirates"
}

def enforce_iso_names(data, country_col, ref_df, iso_col="iso3", ref_name_col="name", score_threshold=85):
    choices = ref_df[ref_name_col].dropna().unique().tolist()
    choices_lower = [c.lower() for c in choices]

    def best_match(x):
        if pd.isna(x):
            return None

        x_norm = str(x).strip().lower()

        # Step 1: Manual overrides
        if x_norm in manual_map:
            return manual_map[x_norm]

        # Step 2: Exact match against ref
        if x_norm in ref_df["name_normalized"].values:
            return ref_df.loc[ref_df["name_normalized"] == x_norm, ref_name_col].values[0]

        # Step 3: Fuzzy match only if high confidence
        match, score, _ = process.extractOne(x_norm, choices_lower)
        if score >= score_threshold:
            idx = choices_lower.index(match)
            return choices[idx]

        # Step 4: If nothing works → Unmatched
        return "Unmatched"

    # Apply matching
    data["destination_country_cleaned"] = data[country_col].apply(best_match)

    # Merge to get ISO code
    data = data.merge(ref_df[[iso_col, ref_name_col]],
                  left_on="destination_country_cleaned",
                  right_on=ref_name_col,
                  how="left")

    data = data.rename(columns={iso_col: "iso_code"})

    return data

cleaned_df = enforce_iso_names(data, "FOREIGN COUNTRY", ref_df)
print(f"\n Cleaning complete! Every country name standardized to ISO reference")

unmatched = cleaned_df[cleaned_df["destination_country_cleaned"] == "Unmatched"]
if not unmatched.empty:
    print("\n Some rows could not be matched to ISO names. Please review:")
    print(unmatched[["FOREIGN COUNTRY"]].drop_duplicates())

In [ ]:
from rapidfuzz import process
reference_file = r"C:\Users\karti\Downloads\ports.xlsx"
ref_df = pd.read_excel(reference_file)   # reference with only "name"

# Normalize reference names for matching
ref_df["name_normalized"] = ref_df["name"].str.strip().str.lower()

def enforce_port_names(cleaned_df, port_col, ref_df, ref_name_col="name", score_threshold=85):
    choices = ref_df[ref_name_col].dropna().unique().tolist()
    choices_lower = [c.lower() for c in choices]

    def best_match(x):
        if pd.isna(x):
            return None

        x_norm = str(x).strip().lower()

        # Step 1: Exact match
        if x_norm in ref_df["name_normalized"].values:
            return ref_df.loc[ref_df["name_normalized"] == x_norm, ref_name_col].values[0]

        # Step 2: Fuzzy match
        match, score, _ = process.extractOne(x_norm, choices_lower)
        if score >= score_threshold:
            idx = choices_lower.index(match)
            return choices[idx]

        # Step 3: If nothing works → Unmatched
        return "Unmatched"

    # Apply matching
    cleaned_df["port_cleaned"] = cleaned_df[port_col].apply(best_match)

    return data
cleaned_df = enforce_port_names(cleaned_df, "PORT OF LOADING", ref_df)

print("\n Cleaning complete! Every port name standardized to reference list.")
unmatched = cleaned_df[cleaned_df["port_cleaned"] == "Unmatched"]
if not unmatched.empty:
    print("\n Some rows could not be matched to reference port names. Please review:")
    print(unmatched[["PORT OF LOADING"]].drop_duplicates())

# New Section

In [ ]:
pip install rapidfuzz

In [ ]:
import pandas as pd
import numpy as np
from rapidfuzz import process, fuzz
import re

In [ ]:
data1=pd.read_excel('/content/Jan 2024 52 Chp.xlsx')

instruction to add file address

In [ ]:
data1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 33214 entries, 0 to 33213
Data columns (total 25 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   LOCATION              33214 non-null  object
 1   INDIAN PORT           33214 non-null  object
 2   CUSH                  33214 non-null  object
 3   SB NO                 33214 non-null  int64
 4   SB DATE               33214 non-null  datetime64[ns]
 5   IEC                   33214 non-null  object
 6   EXPORTER              33214 non-null  object
 7   Exporter_Address      33214 non-null  object
 8   Exporter_City_State   33205 non-null  object
 9   Exporter_PIN          3264 non-null   float64
 10  IMPORTER              33202 non-null  object
 11  FOREIGN PORT          33214 non-null  object
 12  FOREIGN COUNTRY       33214 non-null  object
 13  INVOICE_NO            33214 non-null  int64
 14  Chapter               33214 non-null  int64
 15  HS CODE               33214 non-null  float64
 16  PRODUCT DESCRIPTION   33214 non-null  object
 17  QUANTITY              33214 non-null  float64
 18  UNIT QUANTITY         33214 non-null  object
 19  ITEM_RATE             33214 non-null  float64
 20  Currency              33214 non-null  object
 21  FOB INR               33214 non-null  float64
 22  Exporter_Person_Name  1270 non-null   object
 23  Exporter_Email        2777 non-null   object
 24  Exporter_Contact      2777 non-null   float64
dtypes: datetime64[ns](1), float64(6), int64(3), object(15)
memory usage: 6.3+ MB

In [ ]:
# Selection of specific columns
data = data1[['SB DATE', 'FOB INR', 'QUANTITY', 'IMPORTER', 'EXPORTER', 'HS CODE', 'PRODUCT DESCRIPTION', 'FOREIGN COUNTRY', 'FOREIGN PORT', 'INDIAN PORT','IEC']]

In [ ]:
#  Data["column name"] = data["column name"].astype(int64 or float64)
data["SB DATE"] = pd.to_datetime(data["SB DATE"], errors="coerce", dayfirst=True)
# it is expected that date values are changed into one format either full numeric or alphanumeric in raw file
data["FOB INR"] = (
    data["FOB INR"]
    .astype(str)
    .str.strip()
    .str.replace(",", "", regex=False) #changes , to empty space like 43,452 -> 43452
    .replace("UNKNOWN", None)
    .astype(float)
)

/tmp/ipython-input-3004196271.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data["SB DATE"] = pd.to_datetime(data["SB DATE"], errors="coerce", dayfirst=True)
/tmp/ipython-input-3004196271.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data["FOB INR"] = (

In [ ]:
data.describe()

,SB DATE,FOB INR,QUANTITY,HS CODE
count,33214,3.321400e+04,33214.000000,3.321400e+04
mean,2024-01-16 15:38:56.629132544,1.524933e+06,10721.058202,5.206903e+07
min,2024-01-01 00:00:00,0.000000e+00,0.000000,5.201001e+07
25%,2024-01-09 00:00:00,2.423760e+05,1572.585000,5.205231e+07
50%,2024-01-17 00:00:00,1.289382e+06,6822.144000,5.207900e+07
75%,2024-01-25 00:00:00,1.944130e+06,10596.435000,5.208519e+07
max,2024-01-31 00:00:00,1.266981e+08,480952.400000,5.212250e+07
std,NaN,2.340964e+06,18284.011705,2.343637e+04

In [ ]:
data.isnull().sum()

SB DATE                 0
FOB INR                 0
QUANTITY                0
IMPORTER               12
EXPORTER                0
HS CODE                 0
PRODUCT DESCRIPTION     0
FOREIGN COUNTRY         0
FOREIGN PORT            0
INDIAN PORT             0
IEC                     0
dtype: int64

In [ ]:
data[["QUANTITY", "FOB INR"]] = data[["QUANTITY", "FOB INR"]].fillna(0)

/tmp/ipython-input-763170549.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data[["QUANTITY", "FOB INR"]] = data[["QUANTITY", "FOB INR"]].fillna(0)

In [ ]:
data[data["IEC"].isnull()]
mask = data["IEC"].isna() & data1["Item_Category_Description"].notna() #checks if iec value is present in the particular column and makes a list of true or false
data.loc[mask, "IEC"] = data1.loc[mask, "Item_Category_Description"] #copy the value to iec

In [ ]:
# List of values that are not acceptable
invalid_values = ["#REF!", "#NAME?", "nana", "NA", "#N/A", "Na"]

# Replace in the whole DataFrame
data = data.replace(invalid_values, "UNKNOWN")
data = data.fillna("UNKNOWN")

In [ ]:
data.isnull().sum()

SB DATE                0
FOB INR                0
QUANTITY               0
IMPORTER               0
EXPORTER               0
HS CODE                0
PRODUCT DESCRIPTION    0
FOREIGN COUNTRY        0
FOREIGN PORT           0
INDIAN PORT            0
IEC                    0
dtype: int64

In [ ]:
unknown_counts = (data == "UNKNOWN").sum()
print(unknown_counts)

SB DATE                 0
FOB INR                 0
QUANTITY                0
IMPORTER               12
EXPORTER                0
HS CODE                 0
PRODUCT DESCRIPTION     0
FOREIGN COUNTRY         0
FOREIGN PORT            0
INDIAN PORT             0
IEC                     0
dtype: int64

In [ ]:
data.describe()

,SB DATE,FOB INR,QUANTITY,HS CODE
count,33214,3.321400e+04,33214.000000,3.321400e+04
mean,2024-01-16 15:38:56.629132544,1.524933e+06,10721.058202,5.206903e+07
min,2024-01-01 00:00:00,0.000000e+00,0.000000,5.201001e+07
25%,2024-01-09 00:00:00,2.423760e+05,1572.585000,5.205231e+07
50%,2024-01-17 00:00:00,1.289382e+06,6822.144000,5.207900e+07
75%,2024-01-25 00:00:00,1.944130e+06,10596.435000,5.208519e+07
max,2024-01-31 00:00:00,1.266981e+08,480952.400000,5.212250e+07
std,NaN,2.340964e+06,18284.011705,2.343637e+04

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 33214 entries, 0 to 33213
Data columns (total 11 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   SB DATE              33214 non-null  datetime64[ns]
 1   FOB INR              33214 non-null  float64
 2   QUANTITY             33214 non-null  float64
 3   IMPORTER             33214 non-null  object
 4   EXPORTER             33214 non-null  object
 5   HS CODE              33214 non-null  float64
 6   PRODUCT DESCRIPTION  33214 non-null  object
 7   FOREIGN COUNTRY      33214 non-null  object
 8   FOREIGN PORT         33214 non-null  object
 9   INDIAN PORT          33214 non-null  object
 10  IEC                  33214 non-null  object
dtypes: datetime64[ns](1), float64(3), object(7)
memory usage: 2.8+ MB

# Column wise cleaning

## foreign country

In [ ]:
from rapidfuzz import process
import pandas as pd

# Reference file countries.csv path to filled in between ""
reference_file = r"/content/countries.csv"
ref_df = pd.read_csv(reference_file,
    sep=";",
    quotechar='"',
    encoding="latin1"
)

# Normalise reference names
ref_df["name_normalized"] = ref_df["name"].str.strip().str.lower()

# Manual overrides
manual_map = {
    "united states": "United States of America",
    "u.s.a": "United States of America",
    "usa": "United States of America",
    "us": "United States of America",
    "america": "United States of America",
    "turkey": "Türkiye",
    "kyr": "KYRGYZ REPUBLIC",
    "uae": "United Arab Emirates"
}

def enforce_iso_names(data, country_col, ref_df, iso_col="iso3", ref_name_col="name", score_threshold=85):
    choices = ref_df[ref_name_col].dropna().unique().tolist()
    choices_lower = [c.lower() for c in choices]

    match_stats = {"manual": 0, "exact": 0, "fuzzy": 0, "unmatched": 0}

    def best_match(x):
        if pd.isna(x):
            match_stats["unmatched"] += 1
            return "Unmatched"

        x_norm = str(x).strip().lower()

        # Step 1: Manual overrides
        if x_norm in manual_map:
            match_stats["manual"] += 1
            return manual_map[x_norm]

        # Step 2: Exact match
        if x_norm in ref_df["name_normalized"].values:
            match_stats["exact"] += 1
            return ref_df.loc[ref_df["name_normalized"] == x_norm, ref_name_col].values[0]

        # Step 3: Fuzzy match
        match, score, _ = process.extractOne(x_norm, choices_lower)
        if score >= score_threshold:
            idx = choices_lower.index(match)
            match_stats["fuzzy"] += 1
            return choices[idx]

        # Step 4: Unmatched
        match_stats["unmatched"] += 1
        return "Unmatched"

    # Apply
    data["destination_country_cleaned"] = data[country_col].apply(best_match)

    # Merge ISO codes
    data = data.merge(ref_df[[iso_col, ref_name_col]],
                      left_on="destination_country_cleaned",
                      right_on=ref_name_col,
                      how="left")

    data = data.rename(columns={iso_col: "iso_code"})

    print("\n Cleaning complete! Every country name standardised to ISO reference.")
    print("\n Summary of match methods:")
    for k, v in match_stats.items():
        print(f" - {k.title()} matches: {v}")

    return data

# Apply function on your dataset
cleaned_df = enforce_iso_names(data, "FOREIGN COUNTRY", ref_df)

# Show unmatched countries (unique only)
unmatched = cleaned_df[cleaned_df["destination_country_cleaned"] == "Unmatched"]
if not unmatched.empty:
    print("\n Some rows could not be matched to ISO names. Please review:")
    print(unmatched[["FOREIGN COUNTRY"]].drop_duplicates())

 Cleaning complete! Every country name standardised to ISO reference.

 Summary of match methods:
 - Manual matches: 1777
 - Exact matches: 28627
 - Fuzzy matches: 2809
 - Unmatched matches: 1

 Some rows could not be matched to ISO names. Please review:
      FOREIGN COUNTRY
15318      KYRGHYSTAN

In [ ]:
data.info()

In [ ]:
data[['FOREIGN COUNTRY','destination_country_cleaned']]

## indian port

In [ ]:
from rapidfuzz import process
import pandas as pd

reference_file = r"/content/ports.xlsx"
ref_df = pd.read_excel(reference_file)   # reference with only "name"

# Normalise reference names for matching
ref_df["name_normalized"] = ref_df["Name"].str.strip().str.lower()

def enforce_port_names(cleaned_df, port_col="INDIAN PORT", ref_df=ref_df, ref_name_col="Name", score_threshold=85):
    choices = ref_df[ref_name_col].dropna().unique().tolist()
    choices_lower = [c.lower() for c in choices]

    stats = {"exact": 0, "fuzzy": 0, "unmatched": 0}

    def best_match(x):
        if pd.isna(x):
            stats["unmatched"] += 1
            return "Unmatched"

        x_norm = str(x).strip().lower()

        # Step 1: Exact match
        if x_norm in ref_df["name_normalized"].values:
            stats["exact"] += 1
            return ref_df.loc[ref_df["name_normalized"] == x_norm, ref_name_col].values[0]

        # Step 2: Fuzzy match
        match = process.extractOne(x_norm, choices_lower)
        if match:
            match_str, score, _ = match
            if score >= score_threshold:
                idx = choices_lower.index(match_str)
                stats["fuzzy"] += 1
                return choices[idx]

        # Step 3: If nothing works → Unmatched
        stats["unmatched"] += 1
        return "Unmatched"

    # Apply matching
    cleaned_df["INDIAN PORT (cleaned)"] = cleaned_df[port_col].apply(best_match)

    # Print stats
    total = sum(stats.values())
    print("\n✅ Cleaning complete! Every port name standardised to reference list.")
    print(f"\n📊 Match statistics (threshold = {score_threshold}):")
    print(f"  Exact matches   : {stats['exact']} ({stats['exact']/total:.1%})")
    print(f"  Fuzzy matches   : {stats['fuzzy']} ({stats['fuzzy']/total:.1%})")
    print(f"  Unmatched       : {stats['unmatched']} ({stats['unmatched']/total:.1%})")

    # --- Show unmatched values ---
    unmatched = cleaned_df[cleaned_df["INDIAN PORT (cleaned)"] == "Unmatched"]
    if not unmatched.empty:
        print("\n⚠️ Some rows could not be matched to reference port names. Please review:")
        print(unmatched[["INDIAN PORT"]].drop_duplicates())

    return cleaned_df

# --- Run cleaning ---
cleaned_df = enforce_port_names(cleaned_df, "INDIAN PORT", ref_df)

✅ Cleaning complete! Every port name standardised to reference list.

📊 Match statistics (threshold = 85):
  Exact matches   : 23104 (69.6%)
  Fuzzy matches   : 10100 (30.4%)
  Unmatched       : 10 (0.0%)

⚠️ Some rows could not be matched to reference port names. Please review:
                       INDIAN PORT
25821  JODHPUR ICD-BHAGAT (INBGK6)

✅ Cleaning complete! Every port name standardised to reference list.

## foreign port

In [ ]:
import pandas as pd
from rapidfuzz import process, fuzz

# -------------------------------
# Step 1: Load reference data
# -------------------------------
official_df = pd.read_excel("/content/official_port_names.xlsx")   # has PORT_NAME, COUNTRY
countries_df = pd.read_csv(
    '/content/countries.csv',
    sep=";",
    quotechar='"',
    encoding="latin1"
)  # cols: full_name, code

# Map country name -> code
country_map = dict(zip(
    countries_df['full_name'].str.upper().str.strip(),
    countries_df['code'].str.upper().str.strip()
))

# -------------------------------
# Step 2: Clean raw data columns
# -------------------------------
data['FOREIGN PORT'] = data['FOREIGN PORT'].astype(str).str.strip().str.upper()
data['FOREIGN COUNTRY'] = data['FOREIGN COUNTRY'].astype(str).str.strip().str.upper()
data['country_code'] = data['FOREIGN COUNTRY'].map(country_map)

# -------------------------------
# Step 3: Country-aware fuzzy matching
# -------------------------------
def get_foreign_port_match(row, threshold=85):
    port = row['FOREIGN PORT']
    country_code = row['country_code']

    # Restrict candidates to ports of that country
    candidates = official_df.loc[official_df['COUNTRY'] == country_code, 'PORT_NAME']
    candidates = [c.upper() for c in candidates]

    if not candidates:
        return {"Foreign_Port_Cleaned": None, "Score": None, "Status": "NO_CANDIDATES",
                "Official_Country_Code": None}

    result = process.extractOne(port, candidates, scorer=fuzz.ratio)
    if result:
        match, score, _ = result
        if score >= threshold:
            return {"Foreign_Port_Cleaned": match, "Score": score, "Status": "OK",
                    "Official_Country_Code": country_code}
        else:
            return {"Foreign_Port_Cleaned": None, "Score": score, "Status": "LOW_CONFIDENCE",
                    "Official_Country_Code": country_code}
    else:
        return {"Foreign_Port_Cleaned": None, "Score": None, "Status": "NO_MATCH",
                "Official_Country_Code": country_code}

# Apply
results = data.apply(get_foreign_port_match, axis=1)
data = pd.concat([data, results.apply(pd.Series)], axis=1).reset_index(drop=True)

# -------------------------------
# Step 4: Extra conditions
# -------------------------------
data['Port_Changed'] = (
    data['Foreign_Port_Cleaned'].notna() &
    data['FOREIGN PORT'].ne(data['Foreign_Port_Cleaned'])
)

# Country mismatch flag (only for exact matches, not fuzzy)
data = data.merge(
    official_df[['PORT_NAME', 'COUNTRY']],
    left_on='FOREIGN PORT',
    right_on='PORT_NAME',
    how='left',
    suffixes=('', '_Official')
)

data['Country_Mismatch'] = (
    data['PORT_NAME'].notna() &
    data['country_code'].ne(data['COUNTRY'])
)

# Keep only OK matches
df_final = data[data['Status'] == "OK"].copy()

# -------------------------------
# Step 5: Match statistics
# -------------------------------
stats = data['Status'].value_counts(dropna=False).to_dict()
total = len(data)

print("\n✅ FOREIGN PORT cleaning complete.")
print(f"\n📊 Match statistics (threshold = 85):")
for status, count in stats.items():
    print(f"  {status:<15}: {count} ({count/total:.1%})")

# Show unmatched / problematic rows
unmatched = data[data['Status'].isin(["NO_MATCH", "LOW_CONFIDENCE", "NO_CANDIDATES"])]
if not unmatched.empty:
    print("\n⚠️ Some rows could not be matched confidently. Please review:")
    print(unmatched[['FOREIGN PORT', 'FOREIGN COUNTRY', 'Status', 'Score']].drop_duplicates())

✅ FOREIGN PORT cleaning complete.

📊 Match statistics (threshold = 85):
  NO_CANDIDATES  : 31324 (92.6%)
  LOW_CONFIDENCE : 2063 (6.1%)
  OK             : 451 (1.3%)

⚠️ Some rows could not be matched confidently. Please review:
      FOREIGN PORT FOREIGN COUNTRY         Status  Score
0          QINGDAO           CHINA  NO_CANDIDATES    NaN
2       CHITTAGONG      BANGLADESH  NO_CANDIDATES    NaN
3          COLOMBO       SRI LANKA  NO_CANDIDATES    NaN
4         BENAPOLE      BANGLADESH  NO_CANDIDATES    NaN
5         ALTAMIRA          MEXICO  NO_CANDIDATES    NaN
...            ...             ...            ...    ...
32290    MARSEILLE          FRANCE  NO_CANDIDATES    NaN
32490    BUDAPEST,         HUNGARY  NO_CANDIDATES    NaN
32679    ROTTERDAM         GERMANY  NO_CANDIDATES    NaN
32685   COPENHAGEN         DENMARK  NO_CANDIDATES    NaN
32871       BANJUL          GUINEA  NO_CANDIDATES    NaN

[415 rows x 4 columns]

In [ ]:
data[['FOREIGN PORT','Port_Changed']]

      FOREIGN PORT  Port_Changed
0          QINGDAO         False
1          QINGDAO         False
2       CHITTAGONG         False
3          COLOMBO         False
4         BENAPOLE         False
...            ...           ...
33833        OSAKA         False
33834       DURBAN         False
33835      COLOMBO         False
33836      COLOMBO         False
33837      COLOMBO         False

[33838 rows x 2 columns]

Warning: total number of rows (33838) exceeds max_rows (20000). Limiting to first (20000) rows.

## importer name

In [ ]:
import pandas as pd
import re

# --- Step 1: Normalisation Function ---
def normalise_importer(name: str) -> str:
    if pd.isna(name):
        return "UNKNOWN"

    name = str(name).strip().upper()
    name = pd.Series(name).str.replace(r"[.,’’()/]", "", regex=True).iloc[0]
    name = pd.Series(name).str.replace(r"\s+", " ", regex=True).iloc[0]

    # Only symbols → TO ORDER
    if pd.Series(name).str.match(r"^[^\w]*$").iloc[0]:
        return "TO ORDER"

    # Normalise variations of TO ORDER
    name = pd.Series(name).str.replace(r"TO\s+(THE\s+)?ORDER(\s+OF.*)?", "TO ORDER", regex=True).iloc[0]

    # Common rules
    rules = {
        r"\bL\s*T\s*D\b": "LTD",
        r"\bLIMITED\b": "LTD",
        r"\bLIM\b": "LTD",
        r"\bP\s*V\s*T\b": "PVT",
        r"\bPRIVATE\b": "PVT",
        r"\bC\s*O\b": "CO",
        r"\bCOMPANY\b": "CO",
        r"\bINCORPORATED\b": "INC",
        r"\bP\s*L\s*C\b": "PLC",
        r"\bPUBLIC\s+LTD\b": "PLC",
        r"\bLLC\b": "LLC",
        r"\bL\s*L\s*C\b": "LLC",
        r"\bF\s*Z\s*C\b": "FZC"
    }
    for pattern, replacement in rules.items():
        name = re.sub(pattern, replacement, name)

    return name

# --- Step 2: Apply Normalisation ---
data["Importer_Clean"] = data["IMPORTER"].apply(normalise_importer)

# --- Step 3: Drop duplicates + sort ---
unique_importers = sorted(data["Importer_Clean"].drop_duplicates())

# --- Step 4: Fuzzy Matching Clusters ---
def fuzzy_group(names, threshold=85):
    groups = {}
    visited = set()

    for name in names:
        if name in visited:
            continue
        matches = process.extract(name, names, scorer=fuzz.token_sort_ratio, limit=None)
        cluster = [m[0] for m in matches if m[1] >= threshold]
        for c in cluster:
            visited.add(c)
            groups[c] = name   # anchor = first match
    return groups

groups = fuzzy_group(unique_importers)

# --- Step 5: Map back to dataframe ---
data["Importer_Final"] = data["Importer_Clean"].map(groups).fillna(data["Importer_Clean"])

# --- Step 6: Impact Summary ---
# Count how many rows were changed
changed_rows = (data["Importer_Clean"] != data["Importer_Final"]).sum()

print("Total rows:", len(data))
print("Rows changed (fuzzy-matched):", changed_rows)
print("Percentage changed:", round(changed_rows / len(data) * 100, 2), "%")

# Optional: show top 10 examples of changes
print("\nSample changes:")
print(data.loc[data["Importer_Clean"] != data["Importer_Final"],
               ["IMPORTER", "Importer_Clean", "Importer_Final"]].head(10))

Total rows: 33838
Rows changed (fuzzy-matched): 15707
Percentage changed: 46.42 %

Sample changes:
                             IMPORTER             Importer_Clean  \
0                        TO THE ORDER                   TO ORDER
1                        TO THE ORDER                   TO ORDER
3                     TO THE ORDER OF                   TO ORDER
6   TO  THE ORDER OF  KEB  HANA  BANK                   TO ORDER
7                        TO THE ORDER                   TO ORDER
10  TO  THE ORDER OF  KEB  HANA  BANK                   TO ORDER
14         JAMUNA SPINNING MILLS LTD.  JAMUNA SPINNING MILLS LTD
21                       TO THE ORDER                   TO ORDER
23                       TO THE ORDER                   TO ORDER
26                       TO THE ORDER                   TO ORDER

                       Importer_Final
0                          TO ORDER :
1                          TO ORDER :
3                          TO ORDER :
6                          TO ORDER :
7                          TO ORDER :
10                         TO ORDER :
14  JAMUNA HI-TECH SPINNING MILLS LTD
21                         TO ORDER :
23                         TO ORDER :
26                         TO ORDER :

In [ ]:
data[['Importer_Final','IMPORTER']]

## exporter name